### ISSUE TITLE
Exception while sending packets

### ISSUE THREAD

**Issue by QuakyCZ** [LOOHP/HoloMobHealth#10]
Hello,
latest version of plugin (2.2.4.11) throws often this exception. It's probably when mobs are spawned. 

[log.txt](https://www.toptal.com/developers/hastebin/raw/ukupokobag)

**Comment by LOOHP** [comment]
You have to update protocollib

**Comment by QuakyCZ** [comment]
Yeah, that fixed the problem. Thank you.
