### ISSUE TITLE
Is it possible to make the multi line only be enabled for players

### ISSUE THREAD

**Issue by PeterMa9621** [LOOHP/HoloMobHealth#14]
Is it possible to make the multi-line only be enabled for players and one-line for non-players (animals or mobs)?
Currently, if I enable multi-line, every entity will be applied, but I only want multi-line to be applied for players.

Also, is it possible to use scoreboard to implement the multi-line feature (only for players)? https://bukkit.org/threads/tutorial-scoreboards-teams-with-the-bukkit-api.139655/. I think if using scoreboard, it will be more performance friendly?

**Comment by LOOHP** [comment]
Actually, HoloMobHealth right now doesn't work on Players. It only shows mob health.
