### ISSUE TITLE
[Suggestion] Add Support for LevelledMobs

### ISSUE THREAD

**Issue by Chris6ix** [LOOHP/HoloMobHealth#15]
Could you please add Support for [LevelledMobs](https://www.spigotmc.org/resources/levelledmobs.74304/) so that HoloMobHealth doesn't show the Health Display for Mobs from LevelledMobs?

I just added LM to my Server and saw that HoloMobhealth overwrites their Health display, and so doesn't show their level anymore :/

I really love your plugin and would want to continue using it for the normal mobs...

Cheers,
Chris6ix

**Comment by LOOHP** [comment]
You can kinda have the mob levels displayed through HoloMobHealth with javascript placeholders in holomobhealth.
Using [these](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#levelledmobs) from LevelledMobs

**Comment by Chris6ix** [comment]
Mhm...not a very ideal solution, but I have tried it to see how that would look, and it doesn't work...
What do I need to do for it to work?
I downloaded "javascript" from papi and reloaded the plugin
Then I tried to add `%levelledmobs_level%` or `{%levelledmobs_level%}` to the Display Text in HoloMobHealth
And it just looks like this:
![2022-04-12_23 20 30](https://user-images.githubusercontent.com/65610536/163057826-b1f6a807-deae-4411-ae72-ef37e366e380.png)
Or like this...
![2022-04-12_23 23 25](https://user-images.githubusercontent.com/65610536/163057834-40931e81-9a79-4a78-86ec-8d521390c41c.png)

Here are all my placeholder hooks installed:
![2022-04-12_23 24 17](https://user-images.githubusercontent.com/65610536/163057993-6c6875f4-69b3-434c-bb98-dd03616fea7e.png)
Here is also the part in my HoloMobHealth config:
![image](https://user-images.githubusercontent.com/65610536/163058197-f0c6afda-42fa-4592-b931-71ada71a79af.png)

**Comment by Chris6ix** [comment]
The problem is also that now all the mobs show this LevelledMobs health...even the ones that are not from LevelledMobs (Like normal animals) :/

The best thing would just be proper compatibility of LevelledMobs in HoloMobhealth...

**Comment by LOOHP** [comment]
I mean the javascript placeholders in holomobhealth, not papi. Take a look at the `placeholder_scripts` folder in the HoloMobHealth plugin folder

**Comment by Chris6ix** [comment]
Oh...okay, and how do these work? (What do i need to do now?)

**Comment by LOOHP** [comment]
Look at one of the examples in the `placeholder_scripts` folder, basically, you can create your own placeholders to be used in the HoloMobHealth config. It works similar to javascript placeholders in papi.

**Comment by Chris6ix** [comment]
Do I need to know javascript to make this placeholder?
Because I don't understand much in these files :/

**Comment by LOOHP** [comment]
Here's an example of how you would get the level of the mob in levelledmobs
[LevelledMobsLevel.js](https://drive.google.com/file/d/1g74jsZpyQ-QH-XmFVuxVFIUPrSRha8xb/view?usp=sharing)
This file goes into the `plugins/HoloMobHealth/placeholder_scripts/scripts` folder.
Then you'll have to add these lines into the `scripts.yml` in `plugins/HoloMobHealth/placeholder_scripts`
```yaml
LevelledMobsLevel:
  file: LevelledMobsLevel.js
```
Now you will be able to use `{LevelledMobsLevel}` in the config.yml

**Comment by LOOHP** [comment]
A few state flags are added to worldguard. Btw this is a bit off-topic to this ticket. I think opening a new one or asking on my discord server would be better. Closing this for now.
