### ISSUE TITLE
Add EliteMobs support

### ISSUE THREAD

**Issue by apatuka** [LOOHP/HoloMobHealth#16]
Hello !

It's possible to add the same logic as ShowMythicMobsHealth but for EliteMobs ?
Whenever i spawn a EliteMobs, it replaces it's nameplate with the HoloMobHealth nameplate

Also if it's possible to add dynamic placeholders for EliteMobs like Mob Name and Level.

Thank you !

**Comment by LOOHP** [comment]
Currently, there are no plans to hook into more mob plugins. So a "ShowMythicMobsHealth" for EliteMobs might not be available. However. through the use of the Custom JavaScript placeholders built into HoloMobHealth, you can hook into EliteMobs and retrieve mob names and levels. There are a few examples but with MythicMobs in the plugin folder.

**Comment by apatuka** [comment]
I fixed with the Javascript function: 

	function parse() {
			if(LivingEntity.isDead())
				return null;
			
			if (EntityTracker.static.isEliteMob(LivingEntity)) {
				var eliteName = "";
				if(EntityTracker.static.getEliteMobEntity(LivingEntity).getName() != null)
					eliteName = EntityTracker.static.getEliteMobEntity(LivingEntity).getName()+" ";

				return eliteName;
			}

			return null;
		}

		parse();

**Comment by apatuka** [comment]
https://imgur.com/a/S62fp47
