### ISSUE TITLE
Warning in Console

### ISSUE THREAD

**Issue by Chris6ix** [LOOHP/HoloMobHealth#17]
Hey, I just got a warning in my console on server startup from your plugins "HoloMobHealth" and "InteractionVisualizer"
The plugins seem to work fine, but I still wanted to show it to you...maybe you know what that means...

From HoloMobHealth:
`[21:59:03 WARN]: java.lang.NullPointerException: Cannot read the array length because "buf" is null`
`[21:59:03 WARN]:        at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)`
`[21:59:03 WARN]:        at HoloMobHealth-` `2.3.0.0.jar//com.loohp.holomobhealth.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:127)`
`[21:59:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)`
`[21:59:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)`
`[21:59:03 WARN]:        at` `com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)`
`[21:59:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)`
`[21:59:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)`
`[21:59:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

From InteractionVisualizer:
`[21:59:03 WARN]: java.lang.NullPointerException: Cannot read the array length because "buf" is null`
`[21:59:03 WARN]:        at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)`
`[21:59:03 WARN]:        at InteractionVisualizer-` `1.18.0.0.jar//com.loohp.interactionvisualizer.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:126)`
`[21:59:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)`
`[21:59:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)`
`[21:59:03 WARN]:        at` `com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)`
`[21:59:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)`
`[21:59:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)`
`[21:59:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by LOOHP** [comment]
Try deleting the language folder on both HMH and IV's plugin folder.

**Comment by Chris6ix** [comment]
Okay the Warning is gone, thanks :)
