### ISSUE TITLE
Error: Huge error with the mob health displays

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/HoloMobHealth#2]
https://pastebin.com/LvSEujWw

No idea what this is

**Comment by LOOHP** [comment]
This is a warning from viabackwards, not from holomobhealth (which is probably safe to ignore)

**Comment by JustJP2K** [comment]
> 
> 
> This is a warning from viabackwards, not from holomobhealth (which is probably safe to ignore)

any idea how to remove this warning? its constantly spamming the console so fast that its lagging out and i cant even view anything in console anymore

**Comment by LOOHP** [comment]
I am not very sure, I guess you can ask the people over at viabackwards.

**Comment by JustJP2K** [comment]
found the issue. thx
