### ISSUE TITLE
Can't see mob health

### ISSUE THREAD

**Issue by Nymphxyz** [LOOHP/HoloMobHealth#31]
I am using paper server; the Minecraft version is 1.20.4 and the plugin version is 2.3.6.

I can see the plugin is loaded successfully, 

![image](https://github.com/LOOHP/HoloMobHealth/assets/65056401/3abb53de-e51b-42c7-8a9c-e278731c890a)

but I can't see the healthy info in the game. I can only see the damage info.

![image](https://github.com/LOOHP/HoloMobHealth/assets/65056401/f2aa6ff4-6508-44de-8a20-477f5c9ace5e)

:thinking:

**Comment by 7wOv6ySCjo** [comment]
> I am using paper server; the Minecraft version is 1.20.4 and the plugin version is 2.3.6.
> 
> I can see the plugin is loaded successfully,
> 
> ![image](https://private-user-images.githubusercontent.com/65056401/316305601-3abb53de-e51b-42c7-8a9c-e278731c890a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY0OTEsIm5iZiI6MTcxMzY4NjE5MSwicGF0aCI6Ii82NTA1NjQwMS8zMTYzMDU2MDEtM2FiYjUzZGUtZTUxYi00MmM3LThhOWMtZTI3ODczMWM4OTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA3NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMzI2ZWUxOTA5MDJhNTUwOWM4ZDQ0OGJhNzQ0Y2IzMDllMDc2YmMwZDQxMTlhZjE0NTUyMTNiZDYxZTYxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZBF6YiT7PGpIuB4SiHJZAbzcuGJccvm4M8BMt9N6zh4)
> 
> but I can't see the healthy info in the game. I can only see the damage info.
> 
> ![image](https://private-user-images.githubusercontent.com/65056401/316305637-f2aa6ff4-6508-44de-8a20-477f5c9ace5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY0OTEsIm5iZiI6MTcxMzY4NjE5MSwicGF0aCI6Ii82NTA1NjQwMS8zMTYzMDU2MzctZjJhYTZmZjQtNjUwOC00NGRlLThhMjAtNDc3ZjVjOWFjZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA3NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YjFhNDQ3MWZhODg3MGRhNTYxM2RlZTk2NDQ2NjVjYTMzNjVkNWY4NmZmM2UyOWI3ODdhZGZlZGU3ZTlmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I7v_4tr11qjeHLRFTMvjarumO8Y0GgaS4owLYsTQvio)
> 
> 🤔

Likewise, what happened?

**Comment by Nymphxyz** [comment]
> > I am using paper server; the Minecraft version is 1.20.4 and the plugin version is 2.3.6.
> > I can see the plugin is loaded successfully,
> > ![image](https://private-user-images.githubusercontent.com/65056401/316305601-3abb53de-e51b-42c7-8a9c-e278731c890a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY0OTEsIm5iZiI6MTcxMzY4NjE5MSwicGF0aCI6Ii82NTA1NjQwMS8zMTYzMDU2MDEtM2FiYjUzZGUtZTUxYi00MmM3LThhOWMtZTI3ODczMWM4OTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA3NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMzI2ZWUxOTA5MDJhNTUwOWM4ZDQ0OGJhNzQ0Y2IzMDllMDc2YmMwZDQxMTlhZjE0NTUyMTNiZDYxZTYxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZBF6YiT7PGpIuB4SiHJZAbzcuGJccvm4M8BMt9N6zh4)
> > but I can't see the healthy info in the game. I can only see the damage info.
> > ![image](https://private-user-images.githubusercontent.com/65056401/316305637-f2aa6ff4-6508-44de-8a20-477f5c9ace5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODY0OTEsIm5iZiI6MTcxMzY4NjE5MSwicGF0aCI6Ii82NTA1NjQwMS8zMTYzMDU2MzctZjJhYTZmZjQtNjUwOC00NGRlLThhMjAtNDc3ZjVjOWFjZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA3NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YjFhNDQ3MWZhODg3MGRhNTYxM2RlZTk2NDQ2NjVjYTMzNjVkNWY4NmZmM2UyOWI3ODdhZGZlZGU3ZTlmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I7v_4tr11qjeHLRFTMvjarumO8Y0GgaS4owLYsTQvio)
> > 🤔
> 
> Likewise, what happened?

?

I said the issue is I can't see the healthy info.

Even after I attack the creature.

**Comment by Nymphxyz** [comment]
No healthy bar at all.

**Comment by Nymphxyz** [comment]
Hmm...  not sure why but I can see it works. Maybe because I use a better server....
