### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by BrailleBennett** [LOOHP/HoloMobHealth#33]
https://mclo.gs/D2sKWCu

**Comment by BrailleBennett** [comment]
[HoloMobHealth] Unhandled exception number 256 occurred in onPacketSending(PacketEvent) for HoloMobHealth
 Row 1135 Column 2

**Comment by LOOHP** [comment]
Try updating to HMH 2.3.7.1.

**Comment by BrailleBennett** [comment]
Can you send a direct link to this download? The latest version I see on spigotmc, the official source in readme.md, is 2.3.7.
