### ISSUE TITLE
Holo mob health throwing endless errors in console

### ISSUE THREAD

**Issue by Jsaunders411** [LOOHP/HoloMobHealth#39]
Holo mob health is filling my console with endless exceptions errors since  changing to latest stable version of paper 1.21.
[holo mob health exception.docx](https://github.com/user-attachments/files/16322538/holo.mob.health.exception.docx)
 Attached a file of what is flooding my console now.

**Comment by LOOHP** [comment]
Which server implementation do you run?

**Comment by Jsaunders411** [comment]
Paper 1.21 build 105 stable

**Comment by LOOHP** [comment]
Do you have the disableOldApiSupport flag enabled?
