### ISSUE TITLE
Low health shows as all blank hearts

### ISSUE THREAD

**Issue by TheosisOfficial** [LOOHP/HoloMobHealth#40]
Hello, just posting this here in case it was missed on the Spigot forum:
![image](https://github.com/user-attachments/assets/68982073-7056-4ec2-920a-e51e389066b4)
Still applies to Paper 1.21.

**Comment by LOOHP** [comment]
Can you see how low does it start to show as blank?

**Comment by TheosisOfficial** [comment]
> Can you see how low does it start to show as blank?

I can't see the exact value of the health, but I have to assume that it's below 0.5, because one more punch will kill the mob.

**Comment by TheosisOfficial** [comment]
Hello, now when the mob is dead it still shows the half character.
