### ISSUE TITLE
Health bars of tamed wolves include LuckPerms prefix when TAB is installed

### ISSUE THREAD

**Issue by TheosisOfficial** [LOOHP/HoloMobHealth#41]
For some reason, if I have TAB (https://www.spigotmc.org/resources/tab-1-5-1-21.57806/) installed, when a player attacks a tamed wolf, the owner's LuckPerms prefix is prepended to the wolf's health bar. See this screenshot for an example:
![2024-07-26_11 00 45](https://github.com/user-attachments/assets/e3ceb8de-cf5b-498d-a0e3-34677f3db5f2)
Is this an issue that needs to be resolved on TAB's end? If so, what should I tell the dev in order for them to be able to fix it?

**Comment by LOOHP** [comment]
Are you sure this is related to HoloMobHealth? I believe this is an issue that also happens without HMH.

**Comment by TheosisOfficial** [comment]
> Are you sure this is related to HoloMobHealth? I believe this is an issue that also happens without HMH.

You're right, just tested it with a name tag and the same thing happened. Apologies!
