### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by bobhenl** [LOOHP/HoloMobHealth#50]
https://spark.lucko.me/cHMUbcS3uR
Hello, I'd like to ask, isn't HoloMobHealth consuming a bit more than it should? If so, can it be fixed, please?
![image](https://github.com/user-attachments/assets/3b73fc38-023d-470a-8a6b-d7b56e03a918)

Or is there some way for me to fix this? @LOOHP

**Comment by LOOHP** [comment]
Hmm.. 87/10000 of your server tick doesn't seem that high to me.

**Comment by bobhenl** [comment]
Yeah, I just thought compared to other plugins, but it's probably ok then, thanks for response @LOOHP

**Comment by bobhenl** [comment]
But btw sometimes it looks a bit higher https://spark.lucko.me/aiPeQ6JZyj @LOOHP
