### ISSUE TITLE
Grab a new entity id, stop randomizing it and hoping you get lucky. Because when you don't, weird issues happen.

### ISSUE THREAD

**Issue by libraryaddict** [LOOHP/HoloMobHealth#9]
https://github.com/LOOHP/HoloMobHealth/blob/7473113b8d470eb12cbc48958e4e5ea4517ef275/src/main/java/com/loohp/holomobhealth/modules/DamageIndicator.java#L368

**Comment by libraryaddict** [comment]
Eg: https://github.com/libraryaddict/LibsDisguises/blob/master/src/main/java/me/libraryaddict/disguise/utilities/reflection/ReflectionManager.java#L454

**Comment by TheDarthFather** [comment]
This is spawning endless WARNings on my server. 
It will be great if it can be patched.

Thank You!
 
[latest (1).log](https://github.com/LOOHP/HoloMobHealth/files/7521788/latest.1.log)
:)
